name: AirPrint IPP Manual
version: "1.12.0"
slug: airprint
description: AirPrint bridge for network printers that do not support it
url: https://github.com/aaronfagan/ha-airprint
arch:
  - amd64
  - aarch64
init: true
boot: auto
startup: services
host_network: true
homeassistant_api: true
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Printer status API, used by the AirPrint integration
map:
  - addon_config:rw
  - share:rw
options:
  driver_overrides: []
  printers: []
schema:
  driver_overrides:
    - device: str
      model: str
  printers:
    - icon: list(🖨️|📠|📄|📁|☁️|🏢|🏠)?
      name: str
      location: str?
      device: str?
      driver: url?
